In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [82]:
data = pd.read_csv("ex1data2.txt",header=None)

In [83]:
def computeCost(X,y,theta):
    
    m = len(y)
    h = X.dot(theta)
    square_error = (h - y) **2
    return 1/(2*m) * np.sum(square_error)

In [ ]:
def featureNorm

In [95]:
data_n=data.values                   #convert to array
m=len(data_n[:,0])
 
print(len(data_n))
X=np.append(np.ones((m,1)),data_n[:,0].reshape(m,1),axis=1)
X=np.append(X,data_n[:,1].reshape(m,1),axis=1)
print(X.shape)
Y=data_n[:,1].reshape(m,1)

theta=np.zeros((3,1))

computeCost(X,Y,theta)

47
(47, 3)


5.308510638297872

In [85]:
def gradientDescent(X,y,theta,alpha,num_iters):
    
    m = len(y)
    J_history = []
    
    for i in range(num_iters):
        h = X.dot(theta)
        error = np.dot(X.transpose(),(h-y))   #summation(h-y)*X
        print(error)
        descent = alpha * 1/m *error
        theta -= descent
        J_history.append(computeCost(X,y,theta))
        
    return theta,J_history

In [86]:
theta,J_history = gradientDescent(X,y,theta,0.01,400)
print("h(x) = "+ str(round(theta[0,0],2))+"+"+str(round(theta[1,0],2))+"x1")

[[-1.49000e+02]
 [-3.13679e+05]
 [-4.99000e+02]]
[[6.27558400e+06]
 [1.44943224e+10]
 [2.09345619e+07]]
[[-2.89979583e+11]
 [-6.69746246e+14]
 [-9.67335646e+11]]
[[1.33992285e+16]
 [3.09472925e+19]
 [4.46981515e+16]]
[[-6.19144707e+20]
 [-1.42999669e+24]
 [-2.06538936e+21]]
[[2.86091224e+25]
 [6.60765567e+28]
 [9.54364567e+25]]
[[-1.32195572e+30]
 [-3.05323179e+33]
 [-4.40987905e+30]]
[[6.10842547e+34]
 [1.41082175e+38]
 [2.03769439e+35]]
[[-2.82255005e+39]
 [-6.51905310e+42]
 [-9.41567419e+39]]
[[1.30422951e+44]
 [3.01229076e+47]
 [4.35074664e+44]]
[[-6.02651712e+48]
 [-1.39190393e+52]
 [-2.01037079e+49]]
[[2.78470226e+53]
 [6.43163861e+56]
 [9.28941868e+53]]
[[-1.28674100e+58]
 [-2.97189872e+61]
 [-4.29240714e+58]]
[[5.94570709e+62]
 [1.37323978e+66]
 [1.98341357e+63]]
[[-2.74736197e+67]
 [-6.34539627e+70]
 [-9.16485614e+67]]
[[1.26948699e+72]
 [2.93204830e+75]
 [4.23484992e+72]]
[[-5.86598064e+76]
 [-1.35482591e+80]
 [-1.95681783e+77]]
[[2.71052238e+81]
 [6.26031036e+84]
 [9.0419638

C:\Users\user\Anaconda3\envs\Hsu\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in square
  """
C:\Users\user\Anaconda3\envs\Hsu\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in subtract
  # This is added back by InteractiveShellApp.init_path()


[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]]
[[nan]
 [n

In [87]:
#Predict values for population sizes of 35,000 and 70,000
array = np.array([1, 1650,3])
prediction = theta.transpose().dot(array)
print("Predicted price for population size of 35,000 = ",prediction * 10000)



Predicted price for population size of 35,000 =  [nan]
