In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [20]:
data = pd.read_csv("ex1data2.txt",header=None)

In [21]:
def computeCost(X,y,theta):
    
    m = len(y)
    h = X.dot(theta)
    square_error = (h - y) **2
    return 1/(2*m) * np.sum(square_error)

In [22]:
#Normalize features using mean normalization
def featureNormalize(X):
    
    mu = np.mean(X)
    print(mu)
    sigma = np.std(X)
    
    a = X-mu
    X_norm = a/sigma
    return X_norm
    

In [23]:
data_n=data.values                   #convert to array
m=len(data_n[:,0])
 
X=np.array(data_n[:,0])
X=np.append(X.reshape(m,1),data_n[:,1].reshape(m,1),axis=1)

print(X.shape)
#X=np.append(np.ones((m,1)),data_n[:,0].reshape(m,1),axis=1)
X =featureNormalize(X)
print(X.shape)
X=np.append(np.ones((m,1)),X.reshape(m,2),axis=1)
print(X.shape)

Y=data_n[:,2].reshape(m,1)

theta=np.zeros((3,1))

computeCost(X,Y,theta)
print(Y)

(47, 2)
1001.9255319148937
(47, 2)
(47, 3)
[[399900]
 [329900]
 [369000]
 [232000]
 [539900]
 [299900]
 [314900]
 [198999]
 [212000]
 [242500]
 [239999]
 [347000]
 [329999]
 [699900]
 [259900]
 [449900]
 [299900]
 [199900]
 [499998]
 [599000]
 [252900]
 [255000]
 [242900]
 [259900]
 [573900]
 [249900]
 [464500]
 [469000]
 [475000]
 [299900]
 [349900]
 [169900]
 [314900]
 [579900]
 [285900]
 [249900]
 [229900]
 [345000]
 [549000]
 [287000]
 [368500]
 [329900]
 [314000]
 [299000]
 [179900]
 [299900]
 [239500]]


In [15]:
#gradient descent
def gradientDescent(X,y,theta,alpha,num_iters):
    
    m = len(y)
    J_history = []
    
    for i in range(num_iters):
        h = X.dot(theta)
        error = np.dot(X.transpose(),(h-y))   #summation(h-y)*X
        print(error)
        descent = alpha * 1/m *error
        theta -= descent
        J_history.append(computeCost(X,y,theta))
        
    return theta,J_history

In [17]:
theta,J_history = gradientDescent(X,Y,theta,0.01,400)
print("h(x) = "+ str(round(theta[0,0],2))+"+"+str(round(theta[1,0],2))+"x1")

[[ 46032.60374948]
 [-77312.79416927]
 [-40146.2148895 ]]
[[ 45897.0248986 ]
 [-77065.40301363]
 [-40027.55504301]]
[[ 45761.67703185]
 [-76818.98069689]
 [-39909.0976496 ]]
[[ 45626.5645358 ]
 [-76573.51880232]
 [-39790.8465396 ]]
[[ 45491.6916461 ]
 [-76329.00908487]
 [-39672.80541153]]
[[ 45357.06245171]
 [-76085.44346664]
 [-39554.97783575]]
[[ 45222.6808989 ]
 [-75842.81403264]
 [-39437.36725798]]
[[ 45088.55079524]
 [-75601.1130265 ]
 [-39319.97700272]]
[[ 44954.67581338]
 [-75360.33284639]
 [-39202.81027665]]
[[ 44821.05949482]
 [-75120.46604109]
 [-39085.87017185]]
[[ 44687.7052535 ]
 [-74881.50530602]
 [-38969.15966899]]
[[ 44554.61637938]
 [-74643.44347951]
 [-38852.68164039]]
[[ 44421.79604182]
 [-74406.27353913]
 [-38736.43885304]]
[[ 44289.24729298]
 [-74169.98859808]
 [-38620.43397153]]
[[ 44156.97307101]
 [-73934.58190174]
 [-38504.66956087]]
[[ 44024.97620326]
 [-73700.04682424]
 [-38389.14808926]]
[[ 43893.25940937]
 [-73466.3768652 ]
 [-38273.87193078]]
[[ 43761.82530

In [32]:
#Predict values for population sizes of 35,000 and 70,000
array = np.array([1, 1650,3])
prediction = theta.transpose().dot(array)
print("Predicted price for population size of 35,000 = ",prediction * 10000)



Predicted price for population size of 35,000 =  [2.24066683e+12]
